### ISSUE TITLE
Conversion to numpy

### ISSUE THREAD

**Issue by phiwei** [pytorch/accimage#26]
Hi, 

is it possible to convert an image that was loaded to numpy? I would like to load images with accimage but then chain a custom image transform in CV2. np.asarray() seems to do nothing. 

Thanks!

**Comment by willprice** [comment]
Sure, check out https://github.com/pytorch/accimage/blob/master/test.py#L12

**Comment by phiwei** [comment]
Great, thanks for the amazingly fast answer!
