### ISSUE TITLE
chicago.jpg is absent

### ISSUE THREAD

**Issue by aromnvidia** [pytorch/accimage#7]
test.py loads chicago.jpg by default but this file is not shipped with the source code.

**Comment by Maratyszcza** [comment]
cc @colesbury

**Comment by colesbury** [comment]
@Maratyszcza, I think you wrote this test file. I added separate tests in torch/vision as part of the vision bindings.

**Comment by aromnvidia** [comment]
yes. I launched test.sh which calls test.py

**Comment by Maratyszcza** [comment]
@colesbury I don't recognize the code. IIRC, someone from FAIR contributed it. I thought it was you, but probably it was @soumith

**Comment by soumith** [comment]
it was indeed @colesbury and I presume the file is https://commons.wikimedia.org/wiki/File:Chicago.jpg

**Comment by colesbury** [comment]
Ummm, no? I definitely did not write test.py

**Comment by soumith** [comment]
okay then it was marat or me. i dont remember anymore :-/

**Comment by aromnvidia** [comment]
The solution is simple. Place any JPEG image and name it chicago.jpg

**Comment by Maratyszcza** [comment]
The file @soumith referenced is under Share-Alike CC license, I added another image under CC0 in #8
