### ISSUE TITLE
Is it possible to make a wheel or conda build for this lib?

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/accimage#9]
Currently accimage is used as a backend for torchvision, however it's not clear how to build it (what dependencies are required etc). I have been trying to build it this morning and it doesn't play nice if libjpeg is already in the system. 

Would it be possible to release a distribution (a wheel or conda tar) of this so it's easier to install?

As a side note, this would allow us to easily install accimage as part of the travis job in torchvision so that we can run the tests that require accimage.

**Comment by yannadani** [comment]
@alykhantejani I am facing the same issue here. Can I know what you did to properly install it?

**Comment by alykhantejani** [comment]
@yannadani Sorry, I haven't been able to install this yet

**Comment by tibi77** [comment]
Is this still open?

**Comment by asanakoy** [comment]
Would be nice to have at least an installation instructions in the repo.

**Comment by LincolnZjx** [comment]
It seems Intel IPP must exists, otherwise no way to use this package.

`python setup.py install --user`

**Comment by willprice** [comment]
accimage is now available on conda-forge, see the README (as of commit  f2738a2 ) for instructions on installation
